version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/data:/app/data

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  playwright:
    build: ./playwright-service
    ports:
      - "4000:4000"
    depends_on:
      - backend
